---
# tasks file for myenv
- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"

- name: upgrade all package (Fedora)
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Fedora"

- name: upgrade all package (RHEL and CentOS)
  yum:
    name: "*"
    state: latest
  when: ansible_distribution != "Fedora"

- name: install pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: "/home/{{ my_user }}/.pyenv"
  become: true
  become_user: "{{ my_user }}"

- name: install rbenv
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: "/home/{{ my_user }}/.rbenv"
  become: true
  become_user: "{{ my_user }}"

- name: install ruby-build
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: "/home/{{ my_user }}/.rbenv/plugins/ruby-build"
  become: true
  become_user: "{{ my_user }}"

- name: define pyenv and rbenv setting
  blockinfile:
    dest: "/home/{{ my_user }}/.bash_profile"
    block: |
      ## pyenv (python)
      if [ -e "$HOME/.pyenv" ]; then
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
      fi

      ## rbenv (ruby)
      if [ -e "$HOME/.rbenv" -o -e "/usr/local/bin/rbenv" ]; then
          export RBENV_ROOT="$HOME/.rbenv"
          export PATH="$RBENV_ROOT/bin:$PATH"
          eval "$(rbenv init -)"
      fi

      ## golang
      if [ -e "$HOME/.go" ]; then
          export GOPATH="$HOME/.go"
          export PATH="$GOPATH/bin:$PATH"
      fi
