---
# defaults file for myenv
proxy_env:
  no_proxy: '*'
#  http_proxy: http://172.16.111.1:8080
#  https_proxy: http://172.16.111.1:8080
my_user: hidepin
packages:
  - tmux
  - emacs
  - subversion
  - git
  - zsh
  - golang
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - openssl-devel

fedora_packages:
  - cmigemo

go_packages:
  - { url: 'golang.org/x/tools/cmd/goimports', bin: 'goimports' }
  - { url: 'github.com/nsf/gocode', bin: 'gocode' }
  - { url: 'github.com/rogpeppe/godef', bin: 'godef' }
  - { url: 'github.com/golang/lint/golint', bin: 'golint' }
  - { url: 'github.com/motemen/gore', bin: 'gore' }
  - { url: 'github.com/mitchellh/gox', bin: 'gox' }

fedora_go_packages:
  - { url: 'github.com/peco/peco/cmd/peco', bin: 'peco' }

git_config_param:
  - { name: 'user.name', value: 'Hidetoshi Imai' }
  - { name: 'user.email', value: 'hidepin@gmail.com' }
  - { name: 'color.ui', value: 'auto' }
